name: serverless
version: '1.35.1'
summary: Build web, mobile, & IoT apps with serverless + AWS, Azure, Google, & more!
description: |
  Build applications comprised of microservices that run in response to events, auto-scale for you, and only charge you when they run. This lowers the total cost of maintaining your apps, enabling you to build more logic, faster.

  The Framework uses new event-driven compute services, like AWS Lambda, Google Cloud Functions, and more. It's a command-line tool, providing scaffolding, workflow automation and best practices for developing and deploying your serverless architecture. It's also completely extensible via plugins.

  Serverless is an MIT open-source project, actively maintained by a full-time, venture-backed team.
grade: stable
confinement: classic

apps:
  serverless:
    command: bin/serverless

parts:
  source:
    plugin: nodejs
    source: .
